import RainbowKitAndChakraProvider from "./RainbowKitAndChakraProvider";
import { Inter } from "next/font/google";

import Layout from "@/components/Layout";
import { EventsProvider } from "@/context/Events";
import { extendTheme } from "@chakra-ui/react";
import { ReadFunctionsProvider } from "@/context/ReadFunctions";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = extendTheme({
  colors: {
    color1: "#1B2030",
    color2: "#010a10",
    color3: "#c80037",
    grey1: "#eeeeee",
    white1: "rgb(252, 252, 252)",
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RainbowKitAndChakraProvider>
          <EventsProvider>
            <ReadFunctionsProvider>
              <Layout>{children}</Layout>
            </ReadFunctionsProvider>
          </EventsProvider>
        </RainbowKitAndChakraProvider>
      </body>
    </html>
  );
}
